### ISSUE TITLE
typedef conflict _G 

### ISSUE THREAD

**Issue by loops-and-spells** [wartoshika/wow-classic-declarations#2]
Is it possible to not define _G as it will conflict with more complete typings for lua.

**Comment by wartoshika** [comment]
Yes this is not optimal. My current idea is to add a dedicated importable file to set `_G`. The default import of the declaration will not alter `_G` and anyone can include a more complete LUA typing file.

Ill try to spend some time during the weekend. You could make a pull request any time if you want to remove this issue before.

**Comment by loops-and-spells** [comment]
I will do thanks!

**Comment by Perryvw** [comment]
Do you really need _G? TypeScriptToLua will translate TypeScript's `globalThis` to _G, which can be used instead.

**Comment by wartoshika** [comment]
`globalThis` is the better solution i think. I currently dont know if there are some lua declarations our there that support globalThis with more concrete implementations than `any`.

Since #3 has been merged and `_G` is removed i close this issue. Reopen it any time of you have still problems.

Thanks!
